backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  media_folder: "static/uploads"
  public_folder: "uploads"
  media_library: "static/uploads"

  colletions:
    - name: "blog"
      label: "Noticias"
      folder: "content/blog"
      create: true
      slug: "{{year}}-{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string", required: true}